import {
  REPEATER_AI_TOOL_DEFINITION,
  CREATE_COLLECTION_AI_TOOL_DEFINITION,
  CREATE_FOLDER_AI_TOOL_DEFINITION,
  CREATE_ENDPOINT_AI_TOOL_DEFINITION,
  SEND_REPEATER_REQUEST_AI_TOOL_DEFINITION,
} from './repeater';
import {
  INVOKER_AI_TOOL_DEFINITION,
  STOP_INVOKER_ATTACK_AI_TOOL_DEFINITION,
  SEND_TO_INTRUDER_AI_TOOL_DEFINITION,
} from './intruder';
import {
  INTERCEPT_AI_TOOL_DEFINITION,
  FORWARD_PAUSED_REQUEST_AI_TOOL_DEFINITION,
  DROP_PAUSED_REQUEST_AI_TOOL_DEFINITION,
} from './intercept';
import {
  BROWSER_AI_TOOL_DEFINITION,
  TOGGLE_BROWSER_CRAWL_AI_TOOL_DEFINITION,
  STOP_BROWSER_CRAWL_AI_TOOL_DEFINITION,
} from './browser';
import { NAVIGATE_TO_APP_AI_TOOL_DEFINITION } from './navigation';
import {
  ADD_SCOPE_TARGET_AI_TOOL_DEFINITION,
  REMOVE_SCOPE_TARGET_AI_TOOL_DEFINITION,
} from './live-traffic';
import type { AppAiToolDefinition } from './types';

export const APP_AI_TOOL_DEFINITIONS: AppAiToolDefinition[] = [
  // Repeater
  REPEATER_AI_TOOL_DEFINITION,
  CREATE_COLLECTION_AI_TOOL_DEFINITION,
  CREATE_FOLDER_AI_TOOL_DEFINITION,
  CREATE_ENDPOINT_AI_TOOL_DEFINITION,
  SEND_REPEATER_REQUEST_AI_TOOL_DEFINITION,

  // Intruder / Invoker
  INVOKER_AI_TOOL_DEFINITION,
  STOP_INVOKER_ATTACK_AI_TOOL_DEFINITION,
  SEND_TO_INTRUDER_AI_TOOL_DEFINITION,

  // Intercept Queue
  INTERCEPT_AI_TOOL_DEFINITION,
  FORWARD_PAUSED_REQUEST_AI_TOOL_DEFINITION,
  DROP_PAUSED_REQUEST_AI_TOOL_DEFINITION,

  // Browser Crawler
  BROWSER_AI_TOOL_DEFINITION,
  TOGGLE_BROWSER_CRAWL_AI_TOOL_DEFINITION,
  STOP_BROWSER_CRAWL_AI_TOOL_DEFINITION,

  // Navigation & Scope
  NAVIGATE_TO_APP_AI_TOOL_DEFINITION,
  ADD_SCOPE_TARGET_AI_TOOL_DEFINITION,
  REMOVE_SCOPE_TARGET_AI_TOOL_DEFINITION,
];
