import type { DrawingTemplate } from '../../types';

export const DRAWING_TEMPLATES: DrawingTemplate[] = [
  {
    id: 'architecture-3tier',
    name: '3-Tier System Architecture',
    description: 'Client, Proxy / Load Balancer, API Backend, and Database nodes',
    elements: [
      // Client
      {
        id: 'arch-client',
        type: 'rectangle',
        x: 60,
        y: 120,
        width: 130,
        height: 70,
        color: '#06b6d4',
        fillColor: 'rgba(6, 182, 212, 0.12)',
        strokeWidth: 2,
        text: 'Browser / Client\n(AppRecon)',
        fontSize: 13,
      },
      // Arrow 1
      {
        id: 'arch-arr-1',
        type: 'arrow',
        x: 190,
        y: 155,
        width: 60,
        height: 0,
        color: '#94a3b8',
        strokeWidth: 2,
      },
      // Proxy
      {
        id: 'arch-proxy',
        type: 'rectangle',
        x: 250,
        y: 120,
        width: 130,
        height: 70,
        color: '#8b5cf6',
        fillColor: 'rgba(139, 92, 246, 0.12)',
        strokeWidth: 2,
        text: 'MITM Proxy\n(Port 8080)',
        fontSize: 13,
      },
      // Arrow 2
      {
        id: 'arch-arr-2',
        type: 'arrow',
        x: 380,
        y: 155,
        width: 60,
        height: 0,
        color: '#94a3b8',
        strokeWidth: 2,
      },
      // API Backend
      {
        id: 'arch-api',
        type: 'rectangle',
        x: 440,
        y: 120,
        width: 140,
        height: 70,
        color: '#3b82f6',
        fillColor: 'rgba(59, 130, 246, 0.12)',
        strokeWidth: 2,
        text: 'Backend Server\n& API Routes',
        fontSize: 13,
      },
      // Arrow 3 (Down to DB)
      {
        id: 'arch-arr-3',
        type: 'arrow',
        x: 510,
        y: 190,
        width: 0,
        height: 60,
        color: '#94a3b8',
        strokeWidth: 2,
      },
      // Database
      {
        id: 'arch-db',
        type: 'ellipse',
        x: 435,
        y: 250,
        width: 150,
        height: 65,
        color: '#ec4899',
        fillColor: 'rgba(236, 72, 153, 0.12)',
        strokeWidth: 2,
        text: 'PostgreSQL / SQLite\nDatabase',
        fontSize: 13,
      },
    ],
  },
  {
    id: 'step-sequence',
    name: 'Step Sequence Pipeline',
    description: 'Horizontal step-by-step pipeline with arrows',
    elements: [
      {
        id: 'seq-1',
        type: 'rectangle',
        x: 50,
        y: 80,
        width: 120,
        height: 55,
        color: '#3b82f6',
        fillColor: 'rgba(59, 130, 246, 0.12)',
        strokeWidth: 2,
        text: '1. Reconnaissance',
        fontSize: 12,
      },
      {
        id: 'seq-arr-1',
        type: 'arrow',
        x: 170,
        y: 107,
        width: 50,
        height: 0,
        color: '#94a3b8',
        strokeWidth: 2,
      },
      {
        id: 'seq-2',
        type: 'rectangle',
        x: 220,
        y: 80,
        width: 120,
        height: 55,
        color: '#8b5cf6',
        fillColor: 'rgba(139, 92, 246, 0.12)',
        strokeWidth: 2,
        text: '2. Interception',
        fontSize: 12,
      },
      {
        id: 'seq-arr-2',
        type: 'arrow',
        x: 340,
        y: 107,
        width: 50,
        height: 0,
        color: '#94a3b8',
        strokeWidth: 2,
      },
      {
        id: 'seq-3',
        type: 'rectangle',
        x: 390,
        y: 80,
        width: 120,
        height: 55,
        color: '#f59e0b',
        fillColor: 'rgba(245, 158, 11, 0.12)',
        strokeWidth: 2,
        text: '3. Fuzzing',
        fontSize: 12,
      },
      {
        id: 'seq-arr-3',
        type: 'arrow',
        x: 510,
        y: 107,
        width: 50,
        height: 0,
        color: '#94a3b8',
        strokeWidth: 2,
      },
      {
        id: 'seq-4',
        type: 'rectangle',
        x: 560,
        y: 80,
        width: 120,
        height: 55,
        color: '#10b981',
        fillColor: 'rgba(16, 185, 129, 0.12)',
        strokeWidth: 2,
        text: '4. Exploitation',
        fontSize: 12,
      },
    ],
  },
];
