import type { AutomationNodeType, NodeCategory, NodeConfig } from './types';

export interface NodeTypeDef {
  type: AutomationNodeType;
  label: string;
  category: NodeCategory;
  iconName: string;
  defaultConfig: NodeConfig;
  description: string;
}

export const NODE_TYPE_REGISTRY: Record<AutomationNodeType, NodeTypeDef> = {
  'trigger:scan-completed': {
    type: 'trigger:scan-completed',
    label: 'Scan Completed',
    category: 'trigger',
    iconName: 'CheckCircle',
    description: 'Fires when a browser crawl finishes',
    defaultConfig: { triggerType: 'trigger:scan-completed' },
  },
  'trigger:scheduled': {
    type: 'trigger:scheduled',
    label: 'Scheduled',
    category: 'trigger',
    iconName: 'Clock',
    description: 'Runs on a cron schedule',
    defaultConfig: { triggerType: 'trigger:scheduled', schedule: '0 */6 * * *' },
  },
  'trigger:manual': {
    type: 'trigger:manual',
    label: 'Manual',
    category: 'trigger',
    iconName: 'Play',
    description: 'Run manually by clicking a button',
    defaultConfig: { triggerType: 'trigger:manual' },
  },
  'trigger:browser-page-crawled': {
    type: 'trigger:browser-page-crawled',
    label: 'Page Crawled',
    category: 'trigger',
    iconName: 'Scan',
    description: 'Fires for each page captured during a browser crawl',
    defaultConfig: { triggerType: 'trigger:browser-page-crawled', host: '', operator: 'contains', value: '' },
  },
  'trigger:intercept-request': {
    type: 'trigger:intercept-request',
    label: 'Intercept Request',
    category: 'trigger',
    iconName: 'Shield',
    description: 'Fires when a request is intercepted by the proxy',
    defaultConfig: { triggerType: 'trigger:intercept-request', method: undefined, host: '', operator: 'contains', value: '' },
  },
  'trigger:websocket-message': {
    type: 'trigger:websocket-message',
    label: 'WebSocket Message',
    category: 'trigger',
    iconName: 'Radio',
    description: 'Fires when a WebSocket message is sent or received',
    defaultConfig: { triggerType: 'trigger:websocket-message', direction: undefined, host: '', operator: 'contains', value: '' },
  },
  'trigger:port-scan-result': {
    type: 'trigger:port-scan-result',
    label: 'Port Scan Result',
    category: 'trigger',
    iconName: 'Network',
    description: 'Fires when a port scan discovers an open port',
    defaultConfig: { triggerType: 'trigger:port-scan-result', port: '' },
  },
  'trigger:live-traffic-captured': {
    type: 'trigger:live-traffic-captured',
    label: 'Live Traffic Captured',
    category: 'trigger',
    iconName: 'Pulse',
    description: 'Fires when live traffic captures a new request',
    defaultConfig: { triggerType: 'trigger:live-traffic-captured', host: '', operator: 'contains', value: '' },
  },
  'condition:status-code': {
    type: 'condition:status-code',
    label: 'Status Code',
    category: 'condition',
    iconName: 'Funnel',
    description: 'Check if HTTP status code matches a value',
    defaultConfig: { conditionType: 'condition:status-code', dataPath: 'statusCode', operator: 'equals', value: '500' },
  },
  'condition:url-contains': {
    type: 'condition:url-contains',
    label: 'URL Contains',
    category: 'condition',
    iconName: 'Funnel',
    description: 'Check if the URL contains a keyword',
    defaultConfig: { conditionType: 'condition:url-contains', dataPath: 'url', operator: 'contains', value: '/api' },
  },
  'condition:body-contains': {
    type: 'condition:body-contains',
    label: 'Body Contains',
    category: 'condition',
    iconName: 'Funnel',
    description: 'Check if response body contains text',
    defaultConfig: { conditionType: 'condition:body-contains', dataPath: 'body', operator: 'contains', value: '' },
  },
  'condition:header-exists': {
    type: 'condition:header-exists',
    label: 'Header Exists',
    category: 'condition',
    iconName: 'Funnel',
    description: 'Check if a specific header is present',
    defaultConfig: { conditionType: 'condition:header-exists', dataPath: 'headers', operator: 'equals', value: 'X-API-Key' },
  },
  'condition:severity': {
    type: 'condition:severity',
    label: 'Severity',
    category: 'condition',
    iconName: 'Funnel',
    description: 'Check if finding severity matches',
    defaultConfig: { conditionType: 'condition:severity', dataPath: 'severity', operator: 'equals', value: 'high' },
  },
  'condition:ai-confidence': {
    type: 'condition:ai-confidence',
    label: 'AI Confidence',
    category: 'condition',
    iconName: 'Funnel',
    description: 'Check if AI confidence is above threshold',
    defaultConfig: { conditionType: 'condition:ai-confidence', dataPath: 'confidence', operator: 'gt', value: '0.8' },
  },
  'condition:method': {
    type: 'condition:method',
    label: 'HTTP Method',
    category: 'condition',
    iconName: 'Funnel',
    description: 'Check if the HTTP method matches (GET, POST, PUT, etc.)',
    defaultConfig: { conditionType: 'condition:method', dataPath: 'method', operator: 'equals', value: 'GET' },
  },
  'condition:content-type': {
    type: 'condition:content-type',
    label: 'Content-TextT',
    category: 'condition',
    iconName: 'Funnel',
    description: 'Check if Content-TextT header matches',
    defaultConfig: { conditionType: 'condition:content-type', dataPath: 'headers.content-type', operator: 'contains', value: 'application/json' },
  },
  'condition:response-size': {
    type: 'condition:response-size',
    label: 'Response Size',
    category: 'condition',
    iconName: 'Funnel',
    description: 'Check if response body size exceeds threshold (bytes)',
    defaultConfig: { conditionType: 'condition:response-size', dataPath: 'body', operator: 'gt', value: '1024' },
  },
  'condition:crawl-status': {
    type: 'condition:crawl-status',
    label: 'Crawl Status',
    category: 'condition',
    iconName: 'Funnel',
    description: 'Check crawl page status (queued, visited, error, blocked)',
    defaultConfig: { conditionType: 'condition:crawl-status', dataPath: 'status', operator: 'equals', value: 'error' },
  },
  'condition:grep-match': {
    type: 'condition:grep-match',
    label: 'Grep Match',
    category: 'condition',
    iconName: 'Funnel',
    description: 'Check if a grep pattern matches the response',
    defaultConfig: { conditionType: 'condition:grep-match', dataPath: 'body', operator: 'regex', value: '' },
  },
  'condition:port-open': {
    type: 'condition:port-open',
    label: 'Port Open',
    category: 'condition',
    iconName: 'Funnel',
    description: 'Check if a specific port was found open in scan results',
    defaultConfig: { conditionType: 'condition:port-open', dataPath: 'ports', operator: 'equals', value: '443' },
  },
  'action:send-to-repeater': {
    type: 'action:send-to-repeater',
    label: 'PaperPlaneTilt to Repeater',
    category: 'action',
    iconName: 'ArrowClockwise',
    description: 'PaperPlaneTilt the request to the Repeater tool',
    defaultConfig: { actionType: 'action:send-to-repeater', params: { tabName: 'Automation replay', source: 'request', open: 'true' } },
  },
  'action:ai-analyze': {
    type: 'action:ai-analyze',
    label: 'AI Analyze',
    category: 'action',
    iconName: 'Sparkle',
    description: 'Run AI analysis on the request/response',
    defaultConfig: { actionType: 'action:ai-analyze', params: { prompt: '', profile: 'security', includeRequest: 'true', includeResponse: 'true' } },
  },
  'action:create-finding': {
    type: 'action:create-finding',
    label: 'Create Finding',
    category: 'action',
    iconName: 'Bug',
    description: 'Create a vulnerability finding',
    defaultConfig: { actionType: 'action:create-finding', params: { title: '', severity: 'medium', description: '', evidenceSource: 'payload' } },
  },
  'action:add-to-report': {
    type: 'action:add-to-report',
    label: 'Add to Report',
    category: 'action',
    iconName: 'FileText',
    description: 'Add findings to a document report',
    defaultConfig: { actionType: 'action:add-to-report', params: { section: '', title: 'FlowArrow Report', content: '', mode: 'append' } },
  },
  'action:send-webhook': {
    type: 'action:send-webhook',
    label: 'PaperPlaneTilt WebhooksLogo',
    category: 'action',
    iconName: 'WebhooksLogo',
    description: 'PaperPlaneTilt data to an external webhook URL',
    defaultConfig: { actionType: 'action:send-webhook', params: { url: '', method: 'POST', headers: '', bodyTemplate: '' } },
  },
  'action:show-notification': {
    type: 'action:show-notification',
    label: 'Notification',
    category: 'action',
    iconName: 'Bell',
    description: 'Show a desktop notification',
    defaultConfig: { actionType: 'action:show-notification', params: { title: 'FlowArrow Alert', body: '', level: 'info' } },
  },
  'action:run-script': {
    type: 'action:run-script',
    label: 'Run Script',
    category: 'action',
    iconName: 'Terminal',
    description: 'Execute a custom shell script',
    defaultConfig: { actionType: 'action:run-script', params: { command: '', workingDirectory: '', timeoutSeconds: '30' } },
  },
  'action:start-crawl': {
    type: 'action:start-crawl',
    label: 'Start Crawl',
    category: 'action',
    iconName: 'Scan',
    description: 'Start a browser crawl against the target URL',
    defaultConfig: { actionType: 'action:start-crawl', params: { url: '', maxDepth: '3', scope: 'same-host' } },
  },
  'action:stop-crawl': {
    type: 'action:stop-crawl',
    label: 'Stop Crawl',
    category: 'action',
    iconName: 'Square',
    description: 'Stop the currently running browser crawl',
    defaultConfig: { actionType: 'action:stop-crawl', params: { crawlId: '{{crawlId}}', scope: 'current' } },
  },
  'action:send-to-intercept': {
    type: 'action:send-to-intercept',
    label: 'PaperPlaneTilt to Intercept',
    category: 'action',
    iconName: 'Shield',
    description: 'PaperPlaneTilt a request to the intercept queue',
    defaultConfig: { actionType: 'action:send-to-intercept', params: { source: 'request', queueMode: 'front', pause: 'true' } },
  },
  'action:start-invoker': {
    type: 'action:start-invoker',
    label: 'Start Intruder',
    category: 'action',
    iconName: 'Lightning',
    description: 'Launch an Intruder attack against a target',
    defaultConfig: { actionType: 'action:start-invoker', params: { mode: 'sniper', target: '', wordlist: '' } },
  },

  'action:port-scan': {
    type: 'action:port-scan',
    label: 'Port Scan',
    category: 'action',
    iconName: 'Network',
    description: 'Run a port scan against a target host',
    defaultConfig: { actionType: 'action:port-scan', params: { target: '', preset: 'web', ports: '' } },
  },
  'action:encode-decode': {
    type: 'action:encode-decode',
    label: 'Encode / Decode',
    category: 'action',
    iconName: 'Code',
    description: 'Encode or decode data (URL, Base64, Hex)',
    defaultConfig: { actionType: 'action:encode-decode', params: { mode: 'encode', codec: 'url', sourceField: 'body' } },
  },
  'action:hash-data': {
    type: 'action:hash-data',
    label: 'Hash Data',
    category: 'action',
    iconName: 'Hash',
    description: 'Hash input data (MD5, SHA-256, SHA-512, etc.)',
    defaultConfig: { actionType: 'action:hash-data', params: { algorithm: 'sha256', sourceField: 'body' } },
  },
  'action:export-json': {
    type: 'action:export-json',
    label: 'Export JSON',
    category: 'action',
    iconName: 'Download',
    description: 'Export workflow data as a JSON file',
    defaultConfig: { actionType: 'action:export-json', params: { filename: '', format: 'pretty', source: 'payload' } },
  },
  'action:connect-cdp': {
    type: 'action:connect-cdp',
    label: 'Connect Inspector',
    category: 'action',
    iconName: 'Plug',
    description: 'Start a CDP session to inspect a browser tab',
    defaultConfig: { actionType: 'action:connect-cdp', params: { targetUrl: '{{url}}', targetMode: 'active-tab', openInspector: 'true' } },
  },
};
