import {
  REPEATER_AI_TOOL_DEFINITION,
  CREATE_COLLECTION_AI_TOOL_DEFINITION,
  CREATE_FOLDER_AI_TOOL_DEFINITION,
  CREATE_ENDPOINT_AI_TOOL_DEFINITION,
} from './repeater';
import { INVOKER_AI_TOOL_DEFINITION } from './invoker';
import { INTERCEPT_AI_TOOL_DEFINITION } from './intercept';
import { BROWSER_AI_TOOL_DEFINITION } from './browser';
import { TERMINAL_AI_TOOL_DEFINITION } from './terminal';
import { DOCUMENTS_AI_TOOL_DEFINITION } from './documents';
import type { AppAiToolDefinition } from './types';

export const APP_AI_TOOL_DEFINITIONS: AppAiToolDefinition[] = [
  REPEATER_AI_TOOL_DEFINITION,
  CREATE_COLLECTION_AI_TOOL_DEFINITION,
  CREATE_FOLDER_AI_TOOL_DEFINITION,
  CREATE_ENDPOINT_AI_TOOL_DEFINITION,
  INVOKER_AI_TOOL_DEFINITION,
  INTERCEPT_AI_TOOL_DEFINITION,
  BROWSER_AI_TOOL_DEFINITION,
  TERMINAL_AI_TOOL_DEFINITION,
  DOCUMENTS_AI_TOOL_DEFINITION,
];
