import {
  REPEATER_AI_TOOL_DEFINITION,
  CREATE_COLLECTION_AI_TOOL_DEFINITION,
  CREATE_FOLDER_AI_TOOL_DEFINITION,
  CREATE_ENDPOINT_AI_TOOL_DEFINITION,
} from './repeater';
import { INTRUDER_AI_TOOL_DEFINITION } from './intruder';
import { INTERCEPT_AI_TOOL_DEFINITION } from './intercept';
import { BROWSER_AI_TOOL_DEFINITION } from './browser';
import { TERMINAL_AI_TOOL_DEFINITION } from './terminal';
import type { AppAiToolDefinition } from './types';

export const APP_AI_TOOL_DEFINITIONS: AppAiToolDefinition[] = [
  REPEATER_AI_TOOL_DEFINITION,
  CREATE_COLLECTION_AI_TOOL_DEFINITION,
  CREATE_FOLDER_AI_TOOL_DEFINITION,
  CREATE_ENDPOINT_AI_TOOL_DEFINITION,
  INTRUDER_AI_TOOL_DEFINITION,
  INTERCEPT_AI_TOOL_DEFINITION,
  BROWSER_AI_TOOL_DEFINITION,
  TERMINAL_AI_TOOL_DEFINITION,
];

